### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by jaredweiss** [caiogondim/bullet-train-oh-my-zsh-theme#102]
[L299](https://github.com/caiogondim/bullet-train-oh-my-zsh-theme/blob/master/bullet-train.zsh-theme#L299) of `bullet-train.zsh-theme` causes a parse error when loading the theme in zgen. 

I believe this bug was introduced in commit [a00dbb2](https://github.com/caiogondim/bullet-train-oh-my-zsh-theme/commit/a00dbb2962d9be20b67245bdddbb71eb2b2223a2)

**Comment by jpawlik** [comment]
I'm experiencing the same parse error with oh-my-zsh.

**Comment by caiogondim** [comment]
Thanks for reporting.
What OS you using?

**Comment by jaredweiss** [comment]
This issue was on Linux (Ubuntu 12.04). I can't seem to reproduce the error on a mac.

**Comment by unixorn** [comment]
What versions of zsh are installed on the Mac and Ubuntu machines?

**Comment by unixorn** [comment]
@jaredweiss, if you change line 299 to
```zsh
if [[ "$BULLETTRAIN_GIT_COLORIZE_DIRTY" == true && $(git status --porcelain --ignore-submodules) ]]; then
```

does that resolve the issue on your ubuntu box without breaking the Mac?

**Comment by jaredweiss** [comment]
@unixorn 
Mac: `zsh 5.0.8 (x86_64-apple-darwin14.4.0)`
Linux: `zsh 4.3.17 (x86_64-unknown-linux-gnu)`

That line doesn't seem to solve the issue on the linux machine.

**Comment by NaiveCAI** [comment]
@jaredweiss 
Hi, i met the same problem today.
May be U can try it  this way:

if [["$BULLETTRAIN_GIT_COLORIZE_DIRTY" == true && $(git status --porcelain --ignore-submodules)]]; then

It seems that it's a syntax problem.

**Comment by KVoll** [comment]
@jaredweiss 
Hi, I also had the same problem.  The error was happening on both Mac and Linux using the same zsh versions as you. The solution posted by @unixorn didn't solve the issue on either machine. 
I was able to fix it by changing line 299 to
```shell 
if [[ $BULLETTRAIN_GIT_COLORIZE_DIRTY == true && -n $(git status --porcelain --ignore-submodules) ]]; then
```
Maybe it'll work for you too. Good luck!

**Comment by unixorn** [comment]
@KVoll what version of zsh are you using?

**Comment by KVoll** [comment]
@unixorn 
Mac: ```zsh 5.0.8 (x86_64-apple-darwin14.4.0)```
Linux: ```zsh 4.3.17 (x86_64-unknown-linux-gnu)```

**Comment by unixorn** [comment]
@KVoll are you going to do a PR with your change? I don't mind making one but you should get the credit for the fix.

**Comment by jaredweiss** [comment]
@KVoll Thanks! your fix worked for me
