### ISSUE TITLE
Re-order segments?

### ISSUE THREAD

**Issue by kevinSuttle** [caiogondim/bullet-train-oh-my-zsh-theme#105]
Is it possible to re-order the segments?

**Comment by caiogondim** [comment]
Not at the moment, but an interesting idea.

**Comment by kevinSuttle** [comment]
OK, thanks.

**Comment by kerrizor** [comment]
You can reorder the segments manually in the theme itself, of course.

**Comment by caiogondim** [comment]
I created this issue to implement your idea without hacking the internals: https://github.com/caiogondim/bullet-train-oh-my-zsh-theme/issues/115
