### ISSUE TITLE
Execution time is show since the first time the segment appears

### ISSUE THREAD

**Issue by caiogondim** [caiogondim/bullet-train-oh-my-zsh-theme#108]
Bug on the segment introduced on https://github.com/caiogondim/bullet-train-oh-my-zsh-theme/pull/106

**Comment by caiogondim** [comment]
@henry40408 Could you push a fix for it?

**Comment by henry40408** [comment]
@caiogondim issue has been fixed

**Comment by dbkaplun** [comment]
@henry40408 you've reverted the new color-configurable logic for the segment with this fix.
