### ISSUE TITLE
Slack link is broken

### ISSUE THREAD

**Issue by walmyrcarvalho** [caiogondim/bullet-train-oh-my-zsh-theme#123]
The link to Slack community isn't working: https://bullet-train-zsh-slack.herokuapp.com/
I'm not an user of it (the Slack, I use the theme), just reporting. :)

**Comment by caiogondim** [comment]
Thanks for the heads up.
This link is deployed on Heroku for free. Which means that, from time to time, it will turn it the Heroku instance.

So, unfortunately, expected bug =)

**Comment by walmyrcarvalho** [comment]
Yeah, I know, we have something for Android Dev BR (http://slack.androiddevbr.org), but I've tried a couple times and couldn't find it working, so I thought it was broken. Glad it isn't. :)
