### ISSUE TITLE
Prompt shows code

### ISSUE THREAD

**Issue by xificurC** [caiogondim/bullet-train-oh-my-zsh-theme#126]
- powerline patched fonts installed
- `ttf-ancient-fonts` installed
- zgen load ok

Resulting prompt looks like this:
```
$(build_prompt)
${fg_bold[default]}$(prompt_char) $reset_color
```

**Comment by caiogondim** [comment]
Which OS, ZSH version and terminal app are you using?

**Comment by xificurC** [comment]
Ubuntu 14.4, zsh 5.2, the default Unity terminal (but tested on xterm with same results). I tried this at home as well with same results, where I run Arch Linux, zsh 5.2 and KDEs default terminal

**Comment by xificurC** [comment]
Further testing shows one might need to `zgen oh-my-zsh` before? Now I see a prompt with garbled fonts ![garbled fonts](https://ipfs.pics/ipfs/QmQnqpENXETzzcTJugphCzGwpY6o45xfUiJx3u4kZaT62N)

**Comment by dawikur** [comment]
Have you tried another font for powerline? I am using Droid Sans Dotted for Powerline and is working fine. Can you check this one, and tell which one are you using?

**Comment by xificurC** [comment]
@dawikur I'm not very well versed in the font configurations, how should I uninstall the previous font and install the one you mentioned?

**Comment by xificurC** [comment]
Found out how to set it for the terminal, works fine now. I will drop a PR for updating the `README` for zgen
