### ISSUE TITLE
Where to put image files.

### ISSUE THREAD

**Issue by almadsen** [caiogondim/bullet-train-oh-my-zsh-theme#131]
I'm not sure if I'm getting it right but I can't make this theme to work, is there a certain place I should place the icon files?

**Comment by caiogondim** [comment]
Those "icons" come from a font.
You have to install a patched font with Powerline symbols.

Instructions here: https://github.com/caiogondim/bullet-train-oh-my-zsh-theme#requirements

Make sure install and use that font on your terminal app of choice.

Let me know if you need more help.

**Comment by almadsen** [comment]
Thanx, I'd figured out myself already but thanx anyway.

**Comment by caiogondim** [comment]
You are welcome.
