### ISSUE TITLE
Parse error line 543

### ISSUE THREAD

**Issue by dortegaoh** [caiogondim/bullet-train-oh-my-zsh-theme#134]
In last version you have a parse error bug in line 543 when i tried to use this theme with oh-my-zsh

**Comment by caiogondim** [comment]
Which OS are you using?

I can't reproduce on OS X.

**Comment by dortegaoh** [comment]
OS X yosemite yes

**Comment by randy909** [comment]
Same problem here on Ubuntu 14.04
zsh 5.0.2 (x86_64-pc-linux-gnu)

**Comment by randy909** [comment]
In the meantime, deleting the prompt_nvm function gets it working again

**Comment by abalabahaha** [comment]
Changing line 543 to `if type nvm >/dev/null 2>&1; then` seems to fix it

**Comment by caiogondim** [comment]
@abalabahaha Would you mind making a pull request with the fix?

**Comment by Lyncredible** [comment]
@caiogondim @abalabahaha This issue is blocking me so I went ahead to create this: https://github.com/caiogondim/bullet-train-oh-my-zsh-theme/pull/139.

**Comment by caiogondim** [comment]
This was already solved in https://github.com/caiogondim/bullet-train-oh-my-zsh-theme/pull/139
