### ISSUE TITLE
Allow human-readable display of execution time

### ISSUE THREAD

**Issue by yongqli** [caiogondim/bullet-train-oh-my-zsh-theme#138]
A very long-running process (several hours) results in a string of unclear numbers. I would like the option to display the execution time as something like `2d3h31m5s` instead of `185465s`. Something like this should work:

    function displaytime {
      local T=$1
      local D=$((T/60/60/24))
      local H=$((T/60/60%24))
      local M=$((T/60%60))
      local S=$((T%60))
      [[ $D > 0 ]] && printf '%dd' $D
      [[ $H > 0 ]] && printf '%dh' $H
      [[ $M > 0 ]] && printf '%dm' $M
      printf '%ds' $S
    }

    prompt_cmd_exec_time() {
      if [[ $BULLETTRAIN_EXEC_TIME_SHOW == false ]]; then
        return
      fi

      local stop=`date +%s`
      local start=${cmd_timestamp:-$stop}
      let local elapsed=$stop-$start
      [ $elapsed -gt $BULLETTRAIN_EXEC_TIME_ELAPSED ] && prompt_segment $BULLETTRAIN_EXEC_TIME_BG $BULLETTRAIN_EXEC_TIME_FG "$(displaytime $elapsed)"
    }

**Comment by caiogondim** [comment]
@yongqli Your idea makes a lot of sense.
Would you mind creating a pull request?

**Comment by vadviktor** [comment]
@yongqli this is a great improvement, looking forward to it :) :+1:
