### ISSUE TITLE
Red blue arrows before main arrow background

### ISSUE THREAD

**Issue by radum** [caiogondim/bullet-train-oh-my-zsh-theme#149]
Hello,

I upgraded to iTerm2 Build 3.0.0 and now I see this:

![image](https://cloud.githubusercontent.com/assets/46779/15926176/6b96f1dc-2e32-11e6-9770-2a20a2e69f0b.png)

Those small red and blue arrows. Is this by design or just a bug?

**Comment by caiogondim** [comment]
I'm using iTerm v2.9 without problems.
![screen shot 2016-06-09 at 13 24 57](https://cloud.githubusercontent.com/assets/33044/15928171/a2b00632-2e45-11e6-8288-4ec46d4e9abb.png)

Will update and try to replicate the bug.

**Comment by radum** [comment]
Hi @caiogondim, did you manage to upgrade and have a look at this one?

**Comment by caiogondim** [comment]
I'm using iTerm2 v3.0.2
![screen shot 2016-06-28 at 22 05 03](https://cloud.githubusercontent.com/assets/33044/16430534/63c21726-3d7c-11e6-9e2d-de2654753222.png)

And could not reproduce the bug.
![screen shot 2016-06-28 at 22 04 50](https://cloud.githubusercontent.com/assets/33044/16430547/6d0959c0-3d7c-11e6-85aa-26fce0cfc8d8.png)

Are you using the last version of [Bullet Train](https://github.com/caiogondim/bullet-train-oh-my-zsh-theme)?

**Comment by radum** [comment]
@caiogondim Yes. But I found the problem. https://iterm2.com/documentation-shell-integration.html

```
Marks
When shell integration is enabled, iTerm2 automatically adds a mark at each command prompt.
Marks are indicated visually by a small blue triangle in the left margin.
```

I removed the Show marks indicators option from pref pane and now it is ok.

Not sure if you can update the theme to handle that triangle also.

Thanks for your help

![image](https://cloud.githubusercontent.com/assets/46779/16445855/90e55410-3ddc-11e6-81ea-e5d2d88c2b54.png)
