### ISSUE TITLE
Tons of extra output in prompt - looks like my "history" is showing

### ISSUE THREAD

**Issue by rfair404** [caiogondim/bullet-train-oh-my-zsh-theme#150]
I've recently tried to install Bullet Train. I have the powerline fonts installed, and the bullet train theme installed per the instructions. 

When I enable the theme in .zshrc (oh btw I use oh-my-zsh) and restart iTerm (3.0.0) I get several hundred lines of unexpected output that looks like my shell history. 

I am not sure if this has been dealt with before. any help would be appreciated. It is probably something silly that I'm doing wrong. 

Here you can get a better sense of what I am seeing: http://recordit.co/R8tbhaKTVb

Any help appreciated!

**Comment by rfair404** [comment]
So, I am not sure why or how this made a difference, but it did resolve the issue. 

I was attempting to isolate what was causing the unwanted output and thought I'd disable some of the outputs. I added
```
BULLETTRAIN_PROMPT_ORDER=(
  git
  context
  dir
  time
)
``` to my .zshrc and problems went away. 

so closing I guess.

**Comment by caiogondim** [comment]
Sorry to hear that.
I'm using iTerm 3.0 as well without major problems.

Will keep an eye on this behaviour and fix it if I can reproduce.

Cheers.
