### ISSUE TITLE
Powerline weird arrow shape

### ISSUE THREAD

**Issue by ImAWizardLizard** [caiogondim/bullet-train-oh-my-zsh-theme#157]
I have recently installed the powerline for oh-my-zsh and I installed all of the 3 fonts that are suggested in the install notes. This is the result i got

![bullet-train](https://cloud.githubusercontent.com/assets/8756962/17454778/1b60e98e-5be6-11e6-8f94-359f3399e563.png)

I thought this was quite abnormal compared to the photos displayed on the README file. I decided to remove the last two fonts out of the 3 suggested and I still had no change, is it strange that this is happening? How can I make it look like the ones displayed on the README?

**Comment by caiogondim** [comment]
You have to adjust the line height on your terminal.
I made a screen record to explain it better: http://u.caiogondim.com/261D1k2V2A1K

**Comment by caiogondim** [comment]
Created an FAQ page as well https://github.com/caiogondim/bullet-train-oh-my-zsh-theme/wiki/FAQ

**Comment by unluisco** [comment]
How I can adjust the line height on Hyper terminal? I have this problem. thanks

**Comment by caiogondim** [comment]
You probably have to adjust the `line-height` CSS property.

**Comment by opiumozor** [comment]
Seems like this doesn't work in iTerm2. Even after increasing the character spacing, I still have the same issue. Any ideas?
