### ISSUE TITLE
Multiple character PROMPT_CHAR

### ISSUE THREAD

**Issue by jzck** [caiogondim/bullet-train-oh-my-zsh-theme#161]
Hi, I've started to use emojis as prompt_char, they are big and need an extra space, but this isn't allowed because of : 

```
if [[ ${#BULLETTRAIN_PROMPT_CHAR} -eq 1 ]]; then
    bt_prompt_char="${BULLETTRAIN_PROMPT_CHAR}"
fi
```

So i'm wondering if this bit of code is superfluous or am i doing it wrong ?

**Comment by dawikur** [comment]
Code is simply assuming prompt that prompt will be one character. I think we can mark "Support multi-char prompt" as enhancement :)
