### ISSUE TITLE
What font is used in screenshots?

### ISSUE THREAD

**Issue by revolter** [caiogondim/bullet-train-oh-my-zsh-theme#169]
Asked via email but got no response. What font is used in the [Screenshots][1]?

  [1]: https://github.com/caiogondim/bullet-train-oh-my-zsh-theme/wiki/Screenshots

**Comment by caiogondim** [comment]
Sorry for the delay

The font is [Adobe Source Code Pro](https://github.com/adobe-fonts/source-code-pro)

Maybe you could help us in the docs putting that information there? =)

**Comment by revolter** [comment]
Done 😄
