### ISSUE TITLE
Text and separator colors different

### ISSUE THREAD

**Issue by revolter** [caiogondim/bullet-train-oh-my-zsh-theme#170]
For some reason, at least visually, it looks like the text and separators are using different colors:

![screen shot 2016-10-05 at 10 29 46](https://cloud.githubusercontent.com/assets/5748627/19104697/b5ad14f2-8ae6-11e6-8e9a-361851d36400.png)

**Comment by caiogondim** [comment]
That same issue was discussed on #90 

Can you check if it solves your problem and, if it does, close the issue?

**Comment by revolter** [comment]
Yep, I use iTerm with transparency. The problem was mentioned in #56 actually. Thanks!

**Comment by haf** [comment]
Set "Keep background colours opaque" 
<img width="292" alt="image" src="https://user-images.githubusercontent.com/193115/100546541-2e4e4f80-3262-11eb-8ff1-a26e32e55dfd.png">
