### ISSUE TITLE
Redundant functionality: hiding segments

### ISSUE THREAD

**Issue by dawikur** [caiogondim/bullet-train-oh-my-zsh-theme#186]
After commit #125 we can hide/show segment in two ways:
1. use `BULLETTRAIN_*_SHOW` variable
2. ammend `BULLETTRAIN_PROMPT_ORDER` to remove it

I would like to remove the first one - this would reduce code size and complexity.
With more and more PRs for new segments I am starting to thing about bullet-train now more as a hackable prompt. I see it as a plugable 'core' (after #125) to which you can add more stuff.

What do you think? Removing `_SHOW` variables would be IMO first step to clean code and allow others to boldly add they own stuff.

**Comment by caiogondim** [comment]
I like the idea 👍 
A breaking change, though.

Let's do this.
The less code the better.

**Comment by dawikur** [comment]
Yes, this is breaking change, unfortunately; that's why I first wanted to get some opinion on it :)

**Comment by gabrielizaias** [comment]
So, this breaking change was merged and no new tag/release was cut? 😞 

I'm all for simplifying the codebase, but I spent an unnecessary amount of time trying to figure out why my configuration wasn't working anymore.

I've opened a PR (#223) with an slight improvement to the README. Maybe it'll save someone else's time in the future.
