### ISSUE TITLE
Add support for multiple custom prompts

### ISSUE THREAD

**Issue by revolter** [caiogondim/bullet-train-oh-my-zsh-theme#190]
Could there be added support for multiple custom prompts? Upon adding a second one, I get the error `prompt_my_custom_func:4: = not found`

**Comment by dawikur** [comment]
There already is!

**Comment by revolter** [comment]
I already tried that :(

**Comment by revolter** [comment]
Found the problem. It was because I was using `if test ...; then` instead of `if [[ ... ]]; then`. Don't ask me why.
