### ISSUE TITLE
How to change BULLETTRAIN_VIRTUALENV_PREFIX from 🐍  to a nice Python logo?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [caiogondim/bullet-train-oh-my-zsh-theme#191]
I would like to change BULLETTRAIN_VIRTUALENV_PREFIX to be a nice little Python logo instead of a snake 🐍. Is it possible?

**Comment by dawikur** [comment]
🐍  is unicode character of code `U+1F40D`. If you only find python logo as a unicode character - yes, then it is possible (I did fail to find one).

**Comment by caiogondim** [comment]
It is possible if you use [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts)
I'm thinking on using this as a default.

**Comment by Tset-Noitamotua** [comment]
Wow! That's awesome ... I was not aware of Nerd Fonts. Got to play with it tomorrow :)

Thank you guys!!!

**Comment by caiogondim** [comment]
Gives us a screenshot of yours after you set it up =)

**Comment by Tset-Noitamotua** [comment]
## before Nerd Fonts ...

![image](https://cloud.githubusercontent.com/assets/5635462/21916198/2c94e616-d93f-11e6-82a2-1b05755d3f6e.png)

![image](https://cloud.githubusercontent.com/assets/5635462/21916204/39898958-d93f-11e6-8a5c-c04a13d66c3d.png)

I liked the sunglasses for untracked files :)
![image](https://cloud.githubusercontent.com/assets/5635462/21916216/50b3f38e-d93f-11e6-9918-06f1b8347e28.png)

On light background ...
![image](https://cloud.githubusercontent.com/assets/5635462/21916283/d7892320-d93f-11e6-881c-1c682d70a17c.png)

![image](https://cloud.githubusercontent.com/assets/5635462/21916543/a0c4fe3e-d941-11e6-9aa3-009f2e90b3ac.png)


## with Nerd Fonts

... to be continued

**Comment by caiogondim** [comment]
Waiting for it =)

**Comment by Tset-Noitamotua** [comment]
so many fonts ... so many icons ... soooooo many choises ... puuhhh :)))

I'll just throw in all the screenshots I did ...

![image](https://cloud.githubusercontent.com/assets/5635462/21958665/01ef7770-dab4-11e6-9bfa-481af7c7bd53.png)

![image](https://cloud.githubusercontent.com/assets/5635462/21958666/08409924-dab4-11e6-9a62-b63417abee51.png)

![image](https://cloud.githubusercontent.com/assets/5635462/21958669/0ee9557c-dab4-11e6-9b8a-38cb2875ee2e.png)

![image](https://cloud.githubusercontent.com/assets/5635462/21958670/1464a6fa-dab4-11e6-87e0-8f80a00f8c1d.png)

![image](https://cloud.githubusercontent.com/assets/5635462/21958673/1bd56a1e-dab4-11e6-8577-1f67641e5257.png)

![image](https://cloud.githubusercontent.com/assets/5635462/21958674/21451bca-dab4-11e6-8087-56cbe50c089e.png)

![image](https://cloud.githubusercontent.com/assets/5635462/21958675/26d101bc-dab4-11e6-9041-a7ca83806fff.png)

![image](https://cloud.githubusercontent.com/assets/5635462/21958677/2da53bd4-dab4-11e6-80ba-0770e11fe1bb.png)

![image](https://cloud.githubusercontent.com/assets/5635462/21958681/34623896-dab4-11e6-8ae3-f4d873e33059.png)

![image](https://cloud.githubusercontent.com/assets/5635462/21958686/42f7acb0-dab4-11e6-9c70-449b69dee386.png)

![image](https://cloud.githubusercontent.com/assets/5635462/21958687/4897752e-dab4-11e6-9aa0-aa3990ae8ec4.png)

![image](https://cloud.githubusercontent.com/assets/5635462/21958688/4f0496da-dab4-11e6-88d4-ed6f5fdf0668.png)

![image](https://cloud.githubusercontent.com/assets/5635462/21958689/59d95ab4-dab4-11e6-8d47-873b86c0c429.png)

![image](https://cloud.githubusercontent.com/assets/5635462/21958690/5fb1804c-dab4-11e6-8dc6-032ee29f6a5d.png)

![image](https://cloud.githubusercontent.com/assets/5635462/21958692/67956d6e-dab4-11e6-89e5-c9afd8438995.png)

![image](https://cloud.githubusercontent.com/assets/5635462/21958693/6f3d27e6-dab4-11e6-9335-be81a7b35206.png)

![image](https://cloud.githubusercontent.com/assets/5635462/21958694/75a040be-dab4-11e6-997a-18079b9e1618.png)

![image](https://cloud.githubusercontent.com/assets/5635462/21958747/6c288a04-dab5-11e6-86fd-aa5c75162f7c.png)

**Comment by Tset-Noitamotua** [comment]
updated [to be continued part](https://cloud.githubusercontent.com/assets/5635462/21958816/014491cc-dab7-11e6-94bc-110fcf612e02.png)

**Comment by Tset-Noitamotua** [comment]
btw. what do you use to record an animated gif like your [preview](https://github.com/caiogondim/bullet-train-oh-my-zsh-theme/blob/master/img/preview.gif)?

**Comment by caiogondim** [comment]
I'm using [Kap app](https://getkap.co/).

**Comment by Tset-Noitamotua** [comment]
@caiogondim  Great app! I like it. Thanks for the hint.

**Comment by marcosgriselli** [comment]
@Tset-Noitamotua is there any additional step other than installing font nerd and setting the unicode character on ~/.zshrc? I can't get it to work. 

I'm using Droid Sans Mono: 
`cd ~/Library/Fonts && curl -fLo "Droid Sans Mono for Powerline Nerd Font Complete.otf" https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20for%20Powerline%20Nerd%20Font%20Complete.otf`

Then on my ~/.zshrc I just want to add some github icons:
`export BULLETTRAIN_GIT_CLEAN=" \f408 \f002 "` // This is just to test I want other icons there.

I might be missing something trivial and Nerd Fonts might not even be installed correctly but I didn't miss anything from their readme.

**Comment by Tset-Noitamotua** [comment]
Hi Marcos, I hope I could give u a better answer ... but I dunno, it's a
while ago that I've played with that. I am moving to Linux now and am
setting up everything from scratch so I'll probably come across this issue
again and maybe can give you a better answer then.

Cheers
Tset

2017-06-04 3:32 GMT+02:00 Marcos Griselli <notifications@github.com>:
