### ISSUE TITLE
Can't trust git status when origin is ahead?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [caiogondim/bullet-train-oh-my-zsh-theme#195]
I did some commits from another PC then back on first PC I did `git status` and expected to be behind origin/master but instead I see a `Your branch is up-to-date with 'origin/master'.` As you can see from `git pull` below origin was ahead of my local state.

So can I not trust `git status`?

![image](https://cloud.githubusercontent.com/assets/5635462/21965681/314898b0-db65-11e6-941a-df3a3c7a8e32.png)

**Comment by dawikur** [comment]
Sorry, but how is this related to this project?

The answer to this question is related directly to the philosophy of git - which is **distributed** version control. `git status` shows status from your **local** repository, it does not check **origin**.

**Comment by Tset-Noitamotua** [comment]
Learned something again. Thanks ;-)

**Comment by Tset-Noitamotua** [comment]
On Windows (I use [Cmder](http://cmder.net/)) git checks local **_and origin_** repository:

![image](https://cloud.githubusercontent.com/assets/5635462/22010253/5ad95f92-dc88-11e6-933d-46df90dd7967.png)

I wonder why it should be different on a Mac?
