### ISSUE TITLE
Bug with github status icons

### ISSUE THREAD

**Issue by juhguu** [caiogondim/bullet-train-oh-my-zsh-theme#20]
Github status icon not working in my terminal. Any idea?
![screen shot 2014-12-23 at 20 23 31](https://cloud.githubusercontent.com/assets/3089854/5544253/9b6230c0-8ae1-11e4-8b4a-d851027473b4.png)
[false advertising] lol :stuck_out_tongue_winking_eye:

**Comment by TimePower** [comment]
Thx, but how to setting for xfce4-terminal??

**Comment by caiogondim** [comment]
@TimePower I don't use xfce, so can not help you on this.
Maybe a search on how to setup Powerline on XFCE might help you.

**Comment by gsklee** [comment]
@caiogondim I've installed `bullet-train` on both my laptop and my remote (didn't install font on remote though). It appears fine on my laptop but when I ssh into my remote, those GitHub icons are broken with the `git_prompt_info:4: character not in range` warning. Did I set up something wrong?

**Comment by caiogondim** [comment]
@gsklee You tried all the possible fixes above?

**Comment by dritter** [comment]
@gsklee @TimePower you should set `export LANG=en_US.utf8` in your `~.zshrc` as @gabrielizaias suggested. That should do the trick. The terminal Emulator does not really matter here.

@caiogondim this is related to https://github.com/robbyrussell/oh-my-zsh/issues/4065

**Comment by richarddewit** [comment]
`export LANG=en_US.utf8` worked for me :+1:
