### ISSUE TITLE
Consider changing icons/adding information to git prompt

### ISSUE THREAD

**Issue by dbkaplun** [caiogondim/bullet-train-oh-my-zsh-theme#28]
See https://github.com/olivierverdier/zsh-git-prompt for inspiration

**Comment by idris** [comment]
:+1:

**Comment by JonasGroeger** [comment]
I actually like it like it is right now. Its not cluttered and thus visually pleasing.

**Comment by caiogondim** [comment]
Thanks for the tip!
Right now we will not work on this.

PRs always welcome.
And you can customize it on the meanwhile.
