### ISSUE TITLE
Test with shellcheck

### ISSUE THREAD

**Issue by caiogondim** [caiogondim/bullet-train-oh-my-zsh-theme#29]
http://www.shellcheck.net/about.html

**Comment by JonasGroeger** [comment]
$ shellcheck bullet-train.zsh-theme 

	In bullet-train.zsh-theme line 423:
	  if [[ (-f *.go(#qN) || -d Godeps || -f glide.yaml) ]]; then
	  ^-- SC1009: The mentioned parser error was in this if expression.
	     ^-- SC1073: Couldn't parse this test expression.
	                ^-- SC1036: '(' is invalid here. Did you forget to escape it?
	                ^-- SC1072: Expected "\\)". Fix any mentioned problems and try again.

This is the only thing. Not sure if this is an error.

**Comment by caiogondim** [comment]
I'm thinking about doing it on an automatic way on Travis CI, like https://github.com/travis-ci/apt-package-whitelist/issues/376

**Comment by dawikur** [comment]
I will handle this one :)

**Comment by caiogondim** [comment]
Ditching this.
Discussion can be found in https://github.com/caiogondim/bullet-train-oh-my-zsh-theme/pull/124
