### ISSUE TITLE
Changes not taking effect

### ISSUE THREAD

**Issue by aquesadagt** [caiogondim/bullet-train-oh-my-zsh-theme#320]
I followed al steps and this is all I can see;

[https://imgur.com/bG9oZUw](url)

I must be missing something really big

This is all i have in my zshrc file:

`export ZSH="/home/aquesada/.oh-my-zsh"
ZSH_THEME="bullet-train"
`

Thank you in advance!

**Comment by prietosanti** [comment]
Hi, 

1. Did you follow the requirements listed [here](https://github.com/caiogondim/bullet-train.zsh#requirements)?
2. Did you put the file _**bullet-train.zsh-theme**_ in _**$ZSH_CUSTOM/themes/**_ ?

**Comment by aquesadagt** [comment]
Hola Prieto!

Disculpa, era un problema mío con las fuentes.

Gracias y un saludo!
