### ISSUE TITLE
List of all colors available?

### ISSUE THREAD

**Issue by naquiroz** [caiogondim/bullet-train-oh-my-zsh-theme#341]
Is there a list or a reference to all the colors I can use to customize the theme?

**Comment by jaskij** [comment]
Digging through the source code, it seems to be passing the color directly to ZSH, using `%F` and `%K`, as [described in section 13.2.5 here in the ZSH manual](https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html). From there, we get to [section 18.7](https://zsh.sourceforge.io/Doc/Release/Zsh-Line-Editor.html#Character-Highlighting), which, in part, says:

> The foreground colour should be set to colour, a decimal integer, the name of one of the eight most widely-supported colours or as a ‘#’ followed by an RGB triplet in hexadecimal format.

From the next paragraph, the basic colors are *black, red, green, yellow, blue, magenta, cyan and white*
