### ISSUE TITLE
Arrows are not displayed with the correct color

### ISSUE THREAD

**Issue by unluisco** [caiogondim/bullet-train-oh-my-zsh-theme#36]
![2015-04-14 at 5 15 pm](https://cloud.githubusercontent.com/assets/6332263/7148611/2577eb52-e2ca-11e4-8839-cb4a5546e61b.png)

**Comment by caiogondim** [comment]
What color scheme and font are you using?
I am using:
- color scheme: tomorrow night eighties
- app: iTerm
- font: Sauce Code Powerline

Could you try with my setup so we can see if there is something wrong with your font or color scheme?

**Comment by unluisco** [comment]
Hi, I'm using:

color scheme: [Seti](https://github.com/mbadolato/iTerm2-Color-Schemes)
app: iTerm
font: [Source Code Pro](https://github.com/powerline/fonts)

**Comment by unluisco** [comment]
Hello again, today iTerm testing various configurations, I managed to find the problem, had the least contrast in high lol

![preferences 2015-05-20 14-49-47](https://cloud.githubusercontent.com/assets/6332263/7735082/60b2d090-ff00-11e4-9286-9f1661fea076.png)

![monosnap 2015-05-20 14-54-59](https://cloud.githubusercontent.com/assets/6332263/7735088/6ea3567a-ff00-11e4-9425-96f2f22289af.png)

**Comment by caiogondim** [comment]
Good to hear that. Closing the issue.
