### ISSUE TITLE
`which nvm` letting it's output escape

### ISSUE THREAD

**Issue by gvillalta99** [caiogondim/bullet-train-oh-my-zsh-theme#38]
This [line](https://github.com/caiogondim/bullet-train-oh-my-zsh-theme/blob/master/bullet-train.zsh-theme#L358) is not handling the output of the command `which`.

Also, nvm is a function, it's presence should be validated with `type` command, I think.

![Screenshot 2015-05-13](https://cloud.githubusercontent.com/assets/396968/7612862/bdfba242-f963-11e4-8d8a-f2e8d22f2b88.png)

**Comment by caiogondim** [comment]
Closed on https://github.com/caiogondim/bullet-train-oh-my-zsh-theme/pull/39
