### ISSUE TITLE
Please add support for hostname display

### ISSUE THREAD

**Issue by seitzbg** [caiogondim/bullet-train-oh-my-zsh-theme#41]
Please add support for hostname display.  This is handy for those of us with more than one machine we work on :)

Thanks!

**Comment by secrettriangle** [comment]
@seitzbg, you can set `BULLETTRAIN_CONTEXT_SHOW = true` or `BULLETTRAIN_DIR_CONTEXT_SHOW = true` to see the hostname. Hope this helps!

**Comment by seitzbg** [comment]
hm thought those were defaults, thanks!

**Comment by caiogondim** [comment]
@secrettriangle Thanks for the support =)
