### ISSUE TITLE
virtualenv icon doesn't appear.

### ISSUE THREAD

**Issue by SanketDG** [caiogondim/bullet-train-oh-my-zsh-theme#43]
The snake doesn't appear. Screen: 

![image](https://cloud.githubusercontent.com/assets/8980971/8272663/8a5875b2-1869-11e5-80ea-ce3730ce1efd.png)

**Comment by caiogondim** [comment]
Which OS are you using?
It should appear since it is just an UTF-8 char.

**Comment by SanketDG** [comment]
Linux Mint 17

**Comment by caiogondim** [comment]
Maybe that is the reason.
I made and tested on OS X.

Do your OS has UTF-8/emoji support?

**Comment by SanketDG** [comment]
Yeah, I had to do [this](https://thomashunter.name/blog/enable-emoji-fonts-on-debian-ubuntu-mint-linux/). It worked then. Closing this.

**Comment by gccpacman** [comment]
I came to the same problem in Arch Linux. And inspired by the pre answers It worked after I install ```ttf-symbola``` package.
