### ISSUE TITLE
X signs instead of arrows

### ISSUE THREAD

**Issue by ilyador** [caiogondim/bullet-train-oh-my-zsh-theme#47]
I tried suggested fonts but I still get Xs instead of arrows

<img width="583" alt="ilyo_ _ilyo_ilyo-audyx____ _zsh_ _solarized_dark_xterm-256color_ _158x40" src="https://cloud.githubusercontent.com/assets/703551/9022766/f20036be-388a-11e5-88c4-d8ef3002b256.png">
 
On mac (10.10.4) terminal

**Comment by caiogondim** [comment]
You already solved this one?
