### ISSUE TITLE
prompt_status:15: command not found: ✘

### ISSUE THREAD

**Issue by conrman** [caiogondim/bullet-train-oh-my-zsh-theme#48]
I'm getting this error on C-c, I'm guessing it's some kind of character compatibility but I have the patched fonts and everything else is fine.

**Comment by caiogondim** [comment]
Which OS and Terminal app are you using?

**Comment by conrman** [comment]
Sorry for late reply!

Mac OSX - El Capitan w/ iTerm2

**Comment by caiogondim** [comment]
Could you `git pull` and retest?

**Comment by caiogondim** [comment]
@conrman Could you re-test?
