### ISSUE TITLE
iTerm2 styles only work in first pane in every tab

### ISSUE THREAD

**Issue by saada** [caiogondim/bullet-train-oh-my-zsh-theme#49]
iTerm2 styles are not working when I open new panes. Only the first pane in every tab looks the way it should. Refer to the below screenshot

![screen shot 2015-08-10 at 4 22 44 pm](https://cloud.githubusercontent.com/assets/1087987/9202993/610e18ca-4009-11e5-86b9-f291d7082a33.png)

**Comment by saada** [comment]
https://gitlab.com/gnachman/iterm2/issues/3762

**Comment by caiogondim** [comment]
:+1:
