### ISSUE TITLE
BULLETTRAIN_DIR_EXTENDED not showing username?

### ISSUE THREAD

**Issue by adamwolf** [caiogondim/bullet-train-oh-my-zsh-theme#51]
Hi!  Loving the theme.

I started a branch to add username and hostname, and I see that BULLETTRAIN_DIR_EXTENDED	is supposed to "Show user and machine in an SCP formatted style."

It doesn't seem to be working, for me at least.  I set it true explicitly, and reloaded the theme, and I still see the path but not $USER@$HOST:$PATH like I would expect.

**Comment by caiogondim** [comment]
I can replicate the bug.
Will work on a fix.

**Comment by caiogondim** [comment]
Set `BULLETTRAIN_DIR_CONTEXT_SHOW` as `true` to see as SCP.
It was not on README.
Just updated.

Let me know if everything is okay.
