### ISSUE TITLE
bullet-train doesn't support 12 hour time format in prompt

### ISSUE THREAD

**Issue by mariozig** [caiogondim/bullet-train-oh-my-zsh-theme#52]
For those who prefer a 12 hour timestamp (am/pm style) it would be nice to support it and have a flag to enable/disable.

I'm going to submit a PR for this in a second but just wanted to open a proper issue for it.

**Comment by robcollins55** [comment]
Hi.  Thanks for adding 12hr time support and it's a fantastic theme.  The %D{%r} switch used in the zsh- theme file however displays a format which is unusual for users of that kind of time, ie it shows as HH:MM:SS PM eg 07:48:34 PM.  Better is to use the switch %D{%l:%M%P} which would display that same time as the much more readable format H:MMpm or 7:48pm.  I changed this for myself so no problem, but maybe worth changing in the official Git file?  Cheers.
