### ISSUE TITLE
Doesn't work well when transparency is on?

### ISSUE THREAD

**Issue by gsklee** [caiogondim/bullet-train-oh-my-zsh-theme#56]
![http://i.imgur.com/MxIheir.png](http://i.imgur.com/MxIheir.png)

**Comment by caiogondim** [comment]
AFAIK no powerline font works properly with transparency in iTerm.
Not sure if an issue with iTerm or the font itself.

If you see any powerline font working with transparency let me know so i can investigate.

**Comment by dritter** [comment]
It is an iTerm problem. Transparency in iTerm only applies to the background (for better contrast), and not to the foreground. The segment separator is a regular character and so transparency does not apply to it. That is the reason why it looks like that..

**Comment by caiogondim** [comment]
@dritter Thanks so much for the clarification.

**Comment by haf** [comment]
Set "Keep background colours opaque" 
<img width="292" alt="image" src="https://user-images.githubusercontent.com/193115/100546541-2e4e4f80-3262-11eb-8ff1-a26e32e55dfd.png">
