### ISSUE TITLE
command not found git_prompt_info

### ISSUE THREAD

**Issue by gregf** [caiogondim/bullet-train-oh-my-zsh-theme#59]
```
zsh --version
zsh 5.0.8 (x86_64-pc-linux-gnu)

prompt_git:12: command not found: git_prompt_info
prompt_git:12: command not found: git_prompt_status
```

**Comment by vadviktor** [comment]
@gregf is your `oh-my-zsh` up-to-date? They are oh-my-zsh specific. https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/git.zsh

**Comment by gregf** [comment]
@vadviktor didn't have oh-my-zsh installed at all. I guess I missed that part in the readme. Working good now. Thank you.
