### ISSUE TITLE
.oh-my-zsh/themes/bullet-train.zsh-theme:46: unmatched "

### ISSUE THREAD

**Issue by alex-leonhardt** [caiogondim/bullet-train-oh-my-zsh-theme#79]
I'm seeing 

```
/Users/me/.oh-my-zsh/themes/bullet-train.zsh-theme:46: unmatched "
```

when I use this theme, can't easily seem to see what's missing here ? 

Alex

**Comment by HaoZeke** [comment]
Also got the same error.

**Comment by Strubbl** [comment]
jup, see PR #78

**Comment by afshinm** [comment]
same here

**Comment by YangjunZhang** [comment]
Got the same error

**Comment by caiogondim** [comment]
Already fixed.
Can you pull and double check if everything is ok?

**Comment by caiogondim** [comment]
Fixing this issue since i got no response on this thread.
Let me know if you encounter a new bug.

**Comment by alex-leonhardt** [comment]
hi, yes, sorry - as far as I remember that was working.
