### ISSUE TITLE
iterm2 tab completion add char

### ISSUE THREAD

**Issue by Opiumozor** [caiogondim/bullet-train-oh-my-zsh-theme#80]
When I auto-complete a command using tab, it add a character at the beginning  of the prompt.

Example:

![ls1](https://cloud.githubusercontent.com/assets/1789007/10173618/8319c97a-66e5-11e5-93f3-8f694c8b3617.png)

![ls2](https://cloud.githubusercontent.com/assets/1789007/10173702/09337a9c-66e6-11e5-8ae3-4372f2c018b2.png)

ls[space][tab] adds a "l" at the beginning of the line and then I can't delete this char.

Only happens when BULLETTRAIN_PROMPT_SEPARATE_LINE is set to true.

Works fine in terminal.app but not in iTerm2.

Any ideas?

**Comment by caiogondim** [comment]
Could you check if it is still happening in the latests version?

**Comment by Opiumozor** [comment]
Still happening with the latest version

**Comment by dritter** [comment]
@Opiumozor what is your locale?

**Comment by Opiumozor** [comment]
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

**Comment by contradictioned** [comment]
I have the same with iterm2; my locale:

```
LANG="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_CTYPE="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_ALL="de_DE.UTF-8"
```
