### ISSUE TITLE
Navigation arrow not visible in ubuntu 14.04

### ISSUE THREAD

**Issue by imjaypatel** [caiogondim/bullet-train-oh-my-zsh-theme#86]
I am using Ubuntu 14.04 and recently I install zsh.

Also I add bullet-train-oh-my-zsh-theme and follow this step.
1. Download the theme
2. Put the file bullet-train.zsh-theme in <b>$ZSH_CUSTOM/themes/</b>
3. Configure the theme in your ~/.zshrc file:
 <code>ZSH_THEME="bullet-train"</code>

Current user logout and again login, my terminal look like this,
![bullet train arrow_edited](https://cloud.githubusercontent.com/assets/7599891/10600696/1dcf0134-772a-11e5-9295-97bb4d7a1fab.png)

As I notice arrow not visible properly in my terminal. I need to the same look like: https://goo.gl/o2RnFB

How to loading navigation arrow image in my terminal?

**Comment by sfarzy** [comment]
Do you have the power line compatible fonts like [Powerline patched fonts] (https://github.com/Lokaltog/powerline-fonts) ?

**Comment by imjaypatel** [comment]
Yes, I have. I downloaded and Run <code>./install.sh</code> to install fonts.

Is there and other configuration required to use this Poweline patched fonts?

**Comment by sfarzy** [comment]
On your terminal change font to any of the newly installed powerline font

**Comment by imjaypatel** [comment]
thank you so much its worked. thanks a lot @sfarzy :) :+1:

**Comment by caiogondim** [comment]
Thank you @sfarzy 
Closing the issue already helped you out @imjaypatel
