### ISSUE TITLE
Extra line at the top of prompt

### ISSUE THREAD

**Issue by mhartington** [caiogondim/bullet-train-oh-my-zsh-theme#87]
I'm getting this extra line at the top of the prompt.

<img width="649" alt="screen shot 2015-10-25 at 9 27 08 pm" src="https://cloud.githubusercontent.com/assets/2835826/10719451/4e27fc8a-7b5f-11e5-9298-1c0e5a47c4c3.png">

I figured adding `BULLETTRAIN_PROMPT_ADD_NEWLINE` and setting it to false would do away with it, but it does not. 

```
export BULLETTRAIN_PROMPT_ADD_NEWLINE=false
```

Is this the correct assumption or is there another setting I could configure?

**Comment by sfarzy** [comment]
It should do fine, can you post your relevant ```.zshrc```

**Comment by mhartington** [comment]
Sure thing.

```
  source ~/antigen/antigen.zsh
  antigen use oh-my-zsh
  antigen bundle zsh-users/zsh-syntax-highlighting
  antigen theme https://github.com/caiogondim/bullet-train-oh-my-zsh-theme bullet-train
  # Tell antigen that you're done.
  antigen apply
  export BULLETTRAIN_TIME_SHOW=false
  export BULLETTRAIN_STATUS_SHOW=false
  export BULLETTRAIN_PROMPT_ADD_NEWLINE=false
```

**Comment by caiogondim** [comment]
I doubled check the code and it seems to be ok.
If you change something in your `.zshrc` you have to source it again or open a new terminal session.

To reload the `.zshrc` do `source ~/.zshrc`.
To open a new terminal session just do `ctrl+T`.

Let us know if it solves your problem.

**Comment by mhartington** [comment]
Yep, sourced my zshrc and still nothing. Even removed all my other code in my zshrc and left just the antigen part. Still getting that new line. My zshrc is here 
https://github.com/mhartington/dotfiles/blob/master/zshrc#L49

**Comment by caiogondim** [comment]
I just checked setting `BULLETTRAIN_PROMPT_ADD_NEWLINE` and it worked.
<img width="1280" alt="screen shot 2015-10-26 at 19 59 25" src="https://cloud.githubusercontent.com/assets/33044/10744902/13628292-7c1c-11e5-8588-53676928bab4.png">

The last commit i'm running is 4cddc84bee26ecd38e59c9d7be0d6ad35f6336d1
Can you check again if your project is up to date?

**Comment by mhartington** [comment]
Thats it! Seems my local copy wasn't up to date as I thought it was. Sorry for the noise!

**Comment by mhartington** [comment]
Just one last question, with antigen, it seems that I have to manual source my zshrc every time (not sure why). Any idea on that?

```
  source ~/antigen/antigen.zsh
  antigen use oh-my-zsh
  antigen bundle zsh-users/zsh-syntax-highlighting
  antigen theme https://github.com/caiogondim/bullet-train-oh-my-zsh-theme bullet-train
  # Tell antigen that you're done.
  antigen apply
  export BULLETTRAIN_TIME_SHOW=false
  export BULLETTRAIN_STATUS_SHOW=false
  export BULLETTRAIN_PROMPT_ADD_NEWLINE=false
  export BULLETTRAIN_GIT_ADDED="%F{black}✚%F{black}"
  export BULLETTRAIN_GIT_MODIFIED="%F{blue}✹%F{black}"
```

**Comment by dritter** [comment]
@mhartington You have to define the variables before you tell antigen to use that theme. That should do it.

**Comment by mhartington** [comment]
Thanks :+1:

**Comment by sfarzy** [comment]
@caiogondim Top line with CPU load, time, date and windows look pretty awesome. How to do it?

**Comment by caiogondim** [comment]
@sfarzy It a tmux theme i made https://github.com/caiogondim/maglev
Let me know if you need help installing it

**Comment by kevinSuttle** [comment]
Is there a setting if you _want_ the extra new line?
