### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by liveashish** [caiogondim/bullet-train-oh-my-zsh-theme#96]
I am getting:
themes/bullet-train.zsh-theme:5: parse error near `\n'

**Comment by caiogondim** [comment]
You running the latest version?
Could you `git pull` just in case?

**Comment by Nuclearfossil** [comment]
First time using this theme and getting a similar error:
~/_nixhome/omzsh_customizations/themes/bullet-train-oh-my-zsh-theme/bullet-train.zsh-theme:299: parse error near `]]'

**Comment by caiogondim** [comment]
Which OS are you using?

**Comment by Nuclearfossil** [comment]
Ubuntu 14 LTS in a Vagrant VM under OSX

**Comment by bdesmarez** [comment]
Same problem here, osX ssh to ubuntu

**Comment by caiogondim** [comment]
Ok. Seems to be a problem on Linux.
Will debug it.

**Comment by justmark** [comment]
Just installed bullet-train on a clean install of Ubuntu 14.04 LTS  with oh-my-zsh.  I'm getting the same parse error near ']]' on line 299, mentioned above.  Am aware you're already looking into this.  Thanks.

**Comment by Talanor** [comment]
Hey. Note, I also have this problem:

```
bullet-train.zsh-theme:299: parse error near `]]'
```

On a fresh zsh 5.0.2 install but don't have it on fresh zsh 5.0.7 and 5.2 installs.
Maybe the problem does not come from the script but from a bug introduced in zsh and fixed in the newest versions?

**Comment by KVoll** [comment]
I believe commit 3f5691e fixes this issue. Can anyone please try again to confirm?

**Comment by justmark** [comment]
@KVoll That worked like a charm!

**Comment by Nuclearfossil** [comment]
I just confirmed that 3f5691e fixes the problem for me.

**Comment by caiogondim** [comment]
Closing the issue.
Thanks again @KVoll for the amazing work.
